### ISSUE TITLE
误删和无法单次删完的问题

### ISSUE THREAD

**Issue by valscox** [LCiZY/-HideTrayIcon#8]
大佬你好，用最新版的程序时发现两个问题：
1.有时会误删没有写进脚本的托盘图标，目前我自己遇到问题的是Watt Toolkit和Logitech G HUB；
2.运行一次vb脚本无法删除所有图标，往往剩下2-3个。每次都需要运行三遍脚本才能删干净。

**Comment by LCiZY** [comment]
#9 感谢指正，已经修复
